config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  resources :pet_search, only: [:index, :create]
end

app/models/application_record.rb
# :nocov:
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end
# :nocov:

app/models/pet.rb
class Pet
  attr_reader :name, :photo, :size, :age, :location

  def initialize(pet_data)
    @name = name_check(pet_data)
    @size = size_check(pet_data)
    @age = age_check(pet_data)
    @location = city_state(pet_data)
    @photo = photo_check(pet_data)
  end

  def photo_check(pet_data)
    if !pet_data["media"].present?
      "No pictures"
    elsif pet_data["media"]["photos"]["photo"].class == Array
      pet_data["media"]["photos"]["photo"][0]["$t"]
    else
      pet_data["media"]["photos"]["photo"]["$t"]
    end
  end

  def city_state(pet_data)
    if !pet_data["contact"].present?
      'No location'
    else
      pet_data["contact"]["city"]["$t"] + ' ' + pet_data["contact"]["state"]["$t"]
    end
  end

  def name_check(pet_data)
    if !pet_data["name"].present?
      'No name'
    else
      pet_data["name"]["$t"]
    end
  end

  def size_check(pet_data)
    if !pet_data["size"].present?
      'No size'
    else
      pet_data["size"]["$t"]
    end
  end

  def age_check(pet_data)
    if !pet_data["age"].present?
      'No age'
    else
      pet_data["age"]["$t"]
    end
  end
end

app/models/picture.rb
class Picture
  attr_reader :name, :breed, :photo

  def initialize(picture_data)
    @name = name_check(picture_data)
    @photo = photo_check(picture_data)
    @breed = breed_check(picture_data)
  end

  def photo_check(picture_data)
    if !picture_data["media"].present?
      "http://photos.petfinder.com/photos/pets/43526885/1/?bust=1546876745&width=60&-pnt.jpg"
    elsif picture_data["media"]["photos"]["photo"].class == Array
      picture_data["media"]["photos"]["photo"][0]["$t"]
    else
      picture_data["media"]["photos"]["photo"]["$t"]
    end
  end

  def breed_check(picture_data)
    if !picture_data["breeds"].present?
      'Unknown'
    elsif picture_data["breeds"]["breed"].class == Array
      picture_data["breeds"]["breed"][0]["$t"]
    else
      picture_data["breeds"]["breed"]["$t"]
    end
  end

  def name_check(picture_data)
    if picture_data["name"].present?
      picture_data["name"]["$t"]
    else
      "None yet"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @picture_day = PictureFacade.new
  end
end

app/controllers/pet_search_controller.rb
class PetSearchController < ApplicationController
  def index
    if params["location"]
      if params["location"].present? && PetFacade.new(pet_search_params).pet_found != "Invalid location"
        @pet_find = PetFacade.new(pet_search_params).pet_found
      else
        flash.now[:notice] = "Location cannot be empty or is incorrect"
        render 'index'
      end
    end
  end

  private
  def pet_search_params
    params.permit(:location, :animal, :age, :size)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class='hero'>
  <div class='hero-inner'>
    <h1 class='catch-message'>Where Pets Adopt People Like You</h1>
    <button class='search-button'><%= button_to 'Search Your Pet', pet_search_index_path, method: :get %></button>
    <div class='search-card'>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetAcquirer</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link rel="stylesheet" href="/main.css" title="CSS" type="text/css" />
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Rajdhani|Pacifico" rel="stylesheet">
  </head>

  <body>
    <% if params[:controller] == 'home' %>
      <%= render "shared/navbar" %>
    <% else  %>
      <%= render "shared/no_icon_navbar" %>
    <% end %>
  </body>
  <%= yield %>
</html>

app/views/pet_find/index.html.erb
<div class='.pet'>
  <%  @pet_find.each do |e| %>
    <%= e.name %>
  <% end %>
</div>

app/views/pet_search/index.html.erb
<form id='pet_form'>
  <%= form_tag("/pet_search", method: "get") do %>
    <%= label_tag(:q, "Location") %>
    <%= text_field_tag(:location)%>

    <%= label_tag(:animal, "Animal") %>
    <%= select_tag "animal", options_for_select(['dog', 'cat', 'bird', 'horse', 'reptile'])%>

    <%= label_tag(:age, "Age") %>
    <%= select_tag "age", options_for_select(['Baby', 'Young', 'Adult', 'Senior'])%>

    <%= label_tag(:size, "Size") %>
    <%= select_tag "size", options_for_select(['S', 'M', 'L', 'XL'])%>

    <%= submit_tag("Submit") %>
  <% end %>
</form>

<div class='container-card-pet'>
  <div class="container">
    <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= notice %></div>
    <% end %>
  </div>
  <% unless @pet_find.nil? %>
  <div class='row'>
    <%  @pet_find.each do |e| %>
    <div class='pet'>
      <p class='photo'><img class='pet-pic' src="<%= e.photo %>" alt="Pet picture"></p>
      <p class='name'><%= e.name %></p>
      <p class='age'> <%= e.age %> </p>
      <p class='size'> <%= e.size %> </p>
      <p class='city-state'> <%= e.location %> </p>
    </div>
    <% end %>
  </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar">
    <span>
      MyPetAcquirer
    </span>
    <div class='icon-pic'>
      <img class='pic-day' src="<%= @picture_day.random_picture.photo %>" alt="Pet picture">
    </div>
</nav>

app/views/shared/_no_icon_navbar.html.erb
<nav class="navbar">
    <span>
      MyPetAcquirer
    </span>
</nav>